### ISSUE TITLE
For those who use a School Chromebook (or for any other reason can't run the code)

### ISSUE THREAD

**Issue by Mbrick2** [BirdLogics/sb3topy#1]
For those who use a School Chromebook (or for any other reason can't run the code) I have created a [Repl](https://replit.com/@Mbrick2/sb3topy) to use it.

**Comment by BirdLogics** [comment]
Here's an updated [Repl](https://replit.com/@jahunsbe/sb3topy) which already has the assets downloaded for each of the examples, significantly improving conversion time. It also has Pygame 2.0.2 installed, which fixes the crash due to an mp3 bug. CairoSVG is also installed so SVGs can be converted.

This can be closed after the Repl has been added to the README.

**Comment by jadasse** [comment]
How do I import my sb3? I am having a bit of trouble.

**Comment by BirdLogics** [comment]
Due to changes to Replit, this no longer seems to be a convenient option.
